version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mini-atm
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: mini-atm
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    container_name: nginx
    volumes:
      - .:/var/www/html
      - nginx:/etc/nginx/conf.d
    env_file: ".env"
    restart: always
    ports:
      - "8045:80"
    depends_on:
      - php
    links:
      - php
    networks:
      - laravel

  # node:
  #   image: node:18
  #   working_dir: /var/www/html
  #   volumes:
  #     - .:/var/www/html
  #   networks:
  #     - laravel
  #   command: sh -c "npm install && npm run build"

volumes:
  dbdata:
  nginx:

networks:
  laravel:
    driver: bridge
